"""Obsidian vault integration for job output."""
import json
from datetime import datetime
from pathlib import Path
from .config import Config


class VaultWriter:
    """Write job data to Obsidian vault."""
    
    def __init__(self, config: Config):
        self.config = config
        self.jobs_dir = config.jobs_dir
        self.daily_dir = config.daily_dir
        self.inbox_dir = config.vault_path / "00-Inbox"
        self.jobs_dir.mkdir(parents=True, exist_ok=True)
        self.daily_dir.mkdir(parents=True, exist_ok=True)
        self.inbox_dir.mkdir(parents=True, exist_ok=True)

    def _safe_filename(self, text: str) -> str:
        """Sanitise text for use in filenames."""
        return str(text).replace("/", "-").replace("\\", "-").strip()
    
    def write_job_to_inbox(self, job: dict) -> Path:
        """Write a scored job to the inbox for processing by the inbox processor.

        The inbox processor will later move this to 06-Career/Jobs/ with
        proper formatting, preserving all scoring data.
        """
        company = self._safe_filename(job.get("company", "Unknown"))
        title = self._safe_filename(job.get("title", "Unknown Role"))
        today = datetime.now().strftime('%Y-%m-%d')
        filename = f"{today}-{company} - {title}.md"
        filepath = self.inbox_dir / filename
        
        score = job.get("score", {})

        content = f"""---
type: job
source: jobsearch-pipeline
status: New
created: {datetime.now().strftime('%Y-%m-%d')}
company: {company}
role: {title}
location: {job.get('location', 'N/A')}
url: {job.get('job_url', '')}
score: {score.get('weighted_total', 0)}
location_score: {score.get('location_score', 0)}
experience_score: {score.get('experience_score', 0)}
skills_score: {score.get('skills_score', 0)}
passes_threshold: {score.get('passes_threshold', False)}
scoring_reasoning: "{score.get('reasoning', 'N/A')}"
---

# {title} at {company}

## Score: {score.get('weighted_total', 0)}/10
- Location: {score.get('location_score', 0)}/10
- Experience: {score.get('experience_score', 0)}/10
- Skills: {score.get('skills_score', 0)}/10
- Reasoning: {score.get('reasoning', 'N/A')}

## Job Details
- **Location:** {job.get('location', 'N/A')}
- **Company:** {company}
- **Source:** {job.get('source', 'N/A')}
- **URL:** {job.get('job_url', 'N/A')}

## Description
{str(job.get('description', 'No description available'))[:3000]}

## Cover Letter
<!-- To be generated by cover letter processor -->

## Application Notes
<!-- Seth's notes -->
"""
        
        filepath.write_text(content)
        return filepath

    def write_job(self, job: dict) -> Path:
        """Write a scored job as an Obsidian note (legacy — now writes to inbox)."""
        return self.write_job_to_inbox(job)
    
    def write_daily_digest(self, results: dict) -> Path:
        """Append daily digest to daily note."""
        today = datetime.now().strftime('%Y-%m-%d')
        filepath = self.daily_dir / f"{today}.md"
        
        entry = f"""

## Job Search Digest - {datetime.now().strftime('%H:%M')}

- Jobs discovered: {results.get('discovered', 0)}
- Deduplicated (already in vault): {results.get('deduped', 0)}
- Pre-filtered (title): {results.get('filtered_title', 0)}
- Pre-filtered (location): {results.get('filtered_location', 0)}
- Jobs scored by LLM: {results.get('scored', 0)}
- Jobs passing threshold (≥{self.config.scoring_rules.get('threshold', 7.5)}): {results.get('passed', 0)}
- Cover letters generated: {results.get('cover_letters', 0)}
- Written to inbox: {results.get('passed', 0)} → /00-Inbox/

### Top Matches
"""
        for job in results.get("top_jobs", [])[:5]:
            score = job.get("score", {})
            entry += f"- **{job.get('title')}** at **{job.get('company')}** — Score: {score.get('weighted_total', 0)}/10\n"
        
        # Append or create
        if filepath.exists():
            existing = filepath.read_text()
            filepath.write_text(existing + entry)
        else:
            filepath.write_text(entry)
        
        return filepath

